### ISSUE TITLE
Error: Unable to resolve module `util` from `/node_modules/multiparty/index.js`: Module does not exist in the module map

### ISSUE THREAD

**Issue by omars94** [omars94/react-native-firebase-starter#8]
bundling failed: Error: Unable to resolve module `util` from `/home/omars/react-native-projects/react-native-firebase-starter/node_modules/multiparty/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.
    at UnableToResolveError (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:772:5)
    at ModuleResolver.resolveDependency (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1719)
    at ResolutionRequest.resolveDependency (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at next (native)
    at step (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at /home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
    at /home/omars/react-native-projects/react-native-firebase-starter/node_modules/metro/src/DeltaBundler/traverseDependencies.js:237:9

**Comment by C2P1** [comment]
Hi @omars94 ,

I'm having the same problem right now. Did you find a solution to this?

Thanks!

**Comment by omars94** [comment]
Hi @C2P1 ,

I solved it by going back in my commits , i had an error that was import form from multiparty and not from native base and that was caused from auto import script

**Comment by omars94** [comment]
@C2P1 if you want i can view your code and search for errors

**Comment by C2P1** [comment]
Hi @omars94 ,

Thanks for offering to view my code, I have however fixed the issue by updating all dependencies. My issue was caused by a problem in one of the versions of a dependency I was using, the author of which has now rolled back that change.

Thanks!
